version: "3.9"

services:   
  mongo_junplid:
    image: mongo:6.0 
    restart: unless-stopped
    env_file: .env.mongo
    volumes:
      - ./data-mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5  
    networks: [rede_junplid]


  postgres_junplid:
    image: postgres:16-alpine
    restart: unless-stopped 
    env_file: .env.pg
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5 
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks: [rede_junplid]

  junplid:
    image: ghcr.io/junplid/core-jun.api:latest
    container_name: junplid
    pull_policy: never
    # restart: unless-stopped
    env_file:
      - ./app/.env
      - ./.env.pg
      - ./.env.mongo
    depends_on:
      postgres_junplid:
        condition: service_healthy
      mongo_junplid:
        condition: service_healthy
    ports:
      - 4000:4000 
    volumes:
      - ./app/database-whatsapp:/app/database-whatsapp
      - ./app/bin:/app/bin
      - ./app/static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:4000/v1/public/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [rede_junplid] 

networks:
  rede_junplid:
    driver: bridge