name: Backend Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Verificar mudanças em arquivos Prisma
        id: check_prisma_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'app/prisma/'; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Verificar mudanças em package.json
        id: check_pkg_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -x 'app/package.json'; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Instala o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Criar arquivos .env
        run: |
          echo "${{ secrets.ENV_APP_FILE }}" > ./app/.env
          echo "${{ secrets.ENV_MONGO_FILE }}" > .env.mongo
          echo "${{ secrets.ENV_PG_FILE }}" > .env.pg

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Instalar dependências do NPM
        working-directory: ./app
        if: steps.check_pkg_changes.outputs.has_changes == 'true'
        run: yarn install --frozen-lockfile

      - name: Gerar Prisma Client
        working-directory: ./app
        if: steps.check_prisma_changes.outputs.has_changes == 'true'
        run: npx prisma generate

      - name: Buildar app
        working-directory: ./app
        run: yarn build

      - name: Preparar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Build da imagem Docker
        run: |
          docker build \
            -f app/Dockerfile.prod \
            -t junplid-core:latest \
            app

      - name: Login no GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag e Push pro GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/junplid:latest
          docker tag junplid-core:latest $IMAGE
          docker push $IMAGE

      - name: Deploy na VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/junplid:latest
            docker-compose -f ${{ secrets.VPS_DEST }}/docker-compose.prod.yml up -d
