name: Backend Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Verificar mudanças em arquivos Prisma
        id: check_prisma_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'app/prisma/'; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Instala o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Criar arquivos .env
        run: |
          echo "${{ secrets.ENV_APP_FILE }}" > ./app/.env
          echo "${{ secrets.ENV_MONGO_FILE }}" > .env.mongo
          echo "${{ secrets.ENV_PG_FILE }}" > .env.pg

      - name: Instalar dependências do NPM
        working-directory: ./app
        run: yarn install --frozen-lockfile

      - name: Gerar Prisma Client
        working-directory: ./app
        if: steps.check_prisma_changes.outputs.has_changes == 'true'
        run: npx prisma generate

      - name: Buildar app
        working-directory: ./app
        run: yarn build

      - name: Preparar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Enviar arquivos para a VPS
        run: |
          rsync -avzr \
            --exclude='src' --exclude='**/*.ts' --exclude='**/*.tsx' \
            --exclude='Dockerfile.dev' --exclude='.env.exemple' \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            ./docker-compose.prod.yml \
            ./app/Dockerfile.prod \
            ./.env.mongo \
            ./.env.pg \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DEST }}

          rsync -avzr \
            --exclude='src' --exclude='**/*.ts' --exclude='**/*.tsx' \
            --exclude='Dockerfile.dev' --exclude='.env.exemple' \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            ./app/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DEST }}/app

      # - name: Reiniciar serviço na VPS
      #   run: |
      #     ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
      #       ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
      #       "cd ${{ secrets.VPS_DEST }} && docker restart junplid"
