name: Backend Deploy

on:
  push:
    branches: [main] # Altere para a branch que você usa para

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Criar .env do app
        run: echo "${{ secrets.ENV_APP_FILE }}" > app/.env

      - name: Criar arquivos .env
        run: |
          echo "${{ secrets.ENV_MONGO_FILE }}" > .env.mongo
          echo "${{ secrets.ENV_PG_FILE }}" > .env.pg

      - name: Instalar dependências e buildar
        working-directory: ./app
        run: |
          yarn install --frozen-lockfile
          npx prisma generate
          yarn build

      - name: Preparar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Enviar arquivos para a VPS
        run: |
          rsync -avzr --delete -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            ./docker-compose.prod.yml \
            ./Dockerfile.prod \
            ./.env.mongo \
            ./.env.pg \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DEST }}

          rsync -avzr --delete -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            ./app/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DEST }}/app

      - name: Subir containers na VPS
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "cd ${{ secrets.VPS_DEST }} && docker compose -f docker-compose.prod.yml up -d --build"
